version: "3"
services:
    base:
        image: dbwebb/courserepo:base
        ports:
            - "8080:80"
        #volumes:
            #- .:/app
            #- ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
    databas:
        image: dbwebb/courserepo:databas
        ports:
            - "10080:80"
        # volumes:
        #     - .:/dbwebb-kurser/databas
    oopython:
        image: dbwebb/courserepo:oopython
        ports:
            - "8080:80"
    linux:
        image: dbwebb/courserepo:linux
        ports:
            - "8080:80"
