services:
    # Complete course repos
    website:
        image: dbwebb/website
        ports: [ "10042:80" ]

    # Complete course repos
    # course-htmlphp:
    #     image: dbwebb/courserepo:htmlphp
    #     ports: [ "10042:80" ]
    course-webtec:
        image: dbwebb/courserepo:webtec
        ports: [ "10042:80" ]
    # course-design:
    #     image: dbwebb/courserepo:design
    #     ports: [ "10042:80" ]
    course-databas:
        image: dbwebb/courserepo:databas
        ports: [ "10042:80" ]
    # course-oophp:
    #     image: dbwebb/courserepo:oophp
    #     ports: [ "10042:80" ]
    # course-ramverk1:
    #     image: dbwebb/courserepo:ramverk1
    #     ports: [ "10042:80" ]
    course-mvc:
        image: dbwebb/courserepo:mvc
        ports: [ "10042:80" ]
    course-python:
        image: dbwebb/courserepo:python
        ports: [ "10042:80" ]
    course-oopython:
        image: dbwebb/courserepo:oopython
        ports: [ "10042:80" ]

    # Course repo
    cli:
        image: dbwebb/courserepo:cli
        volumes: [ ".:/home/dbwebb/repo" ]
    courserepo:
        image: dbwebb/courserepo
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    web:
        image: dbwebb/courserepo:web
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    apache:
        image: dbwebb/courserepo:apache
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]

    # CTF
    ctf:
        image: dbwebb/courserepo:ctf
        volumes: [ ".:/home/dbwebb/repo" ]
    ctf-cli:
        image: dbwebb/courserepo:ctf-cli
        volumes: [ ".:/home/dbwebb/repo" ]
    ctf-apache:
        image: dbwebb/courserepo:ctf-apache
        volumes: [ ".:/home/dbwebb/repo" ]

    # Base images
    base-all:
        image: dbwebb/courserepo:base-all
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    base-apache:
        image: dbwebb/courserepo:base-apache
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    base-all-cli:
        image: dbwebb/courserepo:base-all-cli
        volumes: [ ".:/home/dbwebb/repo" ]
    base-php:
        image: dbwebb/courserepo:base-php
        volumes: [ ".:/home/dbwebb/repo" ]
    base-python:
        image: dbwebb/courserepo:base-python
        volumes: [ ".:/home/dbwebb/repo" ]
    base-node:
        image: dbwebb/courserepo:base-node
        volumes: [ ".:/home/dbwebb/repo" ]
    base:
        image: dbwebb/courserepo:base
        volumes: [ ".:/home/dbwebb/repo" ]

    # Debian installations
    jessie:
        image: dbwebb/courserepo:jessie
        volumes: [ ".:/home/dbwebb/repo" ]
    stretch:
        image: dbwebb/courserepo:stretch
        volumes: [ ".:/home/dbwebb/repo" ]
    buster:
        image: dbwebb/courserepo:buster
        volumes: [ ".:/home/dbwebb/repo" ]
    bullseye:
        image: dbwebb/courserepo:bullseye
        volumes: [ ".:/home/dbwebb/repo" ]
    debian:
        image: dbwebb/courserepo:debian
        volumes: [ ".:/home/dbwebb/repo" ]
