# Use something as base image
FROM dbwebb/courserepo:base
ARG COURSEREPO

# Clone courserepo and install local development environment
RUN git clone https://github.com/dbwebb-se/${COURSEREPO}.git
WORKDIR /dbwebb/$COURSEREPO
RUN make install
ENV PATH="/dbwebb/$COURSEREPO/bin:${PATH}"
RUN dbwebb config create noinput    \
    && dbwebb check                 \
    && dbwebb init-me
